# Generated by Django 3.2.15 on 2022-09-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_remove_serverinstance_stopped_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='clouduser',
            name='server_instance',
            field=models.ManyToManyField(to='rest_api.ServerInstance'),
        ),
        migrations.AddField(
            model_name='clouduser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='serverinstance',
            name='machine_id',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='serverinstance',
            name='public_ip_address',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='serverinstance',
            name='stopped_time',
            field=models.CharField(default='NOT STOPPED', max_length=50),
        ),
        migrations.AddField(
            model_name='serverinstance',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='serverinstance',
            name='usage_hours',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='serverinstance',
            name='create_time',
            field=models.CharField(max_length=50),
        ),
    ]
