# Generated by Django 3.2.15 on 2022-09-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_rename_sever_type_serverinstance_server_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinstance',
            name='user_email',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
