# Generated by Django 3.2.15 on 2022-09-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_serverinstance_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinstance',
            name='subscription_item_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
