# Generated by Django 3.2.15 on 2022-09-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_serverinstance_subscription_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinstance',
            name='password',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
