# Generated by Django 3.2.15 on 2022-09-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_serverinstance_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinstance',
            name='lab_url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
