# Generated by Django 3.2.15 on 2022-09-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_serverinstance_lab_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinstance',
            name='workspace_token',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
