# Generated by Django 3.2.15 on 2022-09-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_serverinstance_workspace_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinstance',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
